// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

/*
Package dongfeng_protobuf is a generated protocol buffer package.

It is generated from these files:
	github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

It has these top-level messages:
	DashboardRequest
	DashboardResponse
	LoginRequest
	LoginResponse
	User
	UploadAvatarResponse
	Setting
	UpdateNotificationsRequest
	UpdateNotificationsResponse
	SaveNotificationRequest
	SaveNotificationResponse
	Notification
	UpdateUserRequest
	UpdateUserResponse
	GetClassRequest
	GetClassResponse
	UpdateClassRequest
	UpdateClassResponse
	Class
	GetPupilRequest
	GetPupilResponse
	UpdatePupilRequest
	UpdatePupilResponse
	Pupil
	GetTeacherRequest
	GetTeacherResponse
	UpdateTeacherRequest
	UpdateTeacherResponse
	Teacher
	UpdateAttendanceRequest
	UpdateAttendanceResponse
	ClassAttendance
	GetAttendanceRequest
	GetAttendanceResponse
	Attendance
	GetAttendanceCountRequest
	GetAttendanceCountResponse
	AttendanceCount
	GetIngredientRequest
	GetIngredientResponse
	UpdateIngredientRequest
	UpdateIngredientResponse
	Ingredient
	IngredientNutrition
	GetRecipeRequest
	GetRecipeResponse
	UpdateRecipeRequest
	UpdateRecipeResponse
	Recipe
	IngredientUnitAmount
	RecipeNutrition
	GetProcurementRequest
	GetProcurementResponse
	Procurement
	IngredientAmount
	GetMenuRequest
	GetMenuResponse
	UpdateMenuRequest
	UpdateMenuResponse
	Menu
	UpdatePhysiqueRequest
	UpdatePhysiqueResponse
	Physique
	PhysiqueItem
	GetPhysiqueRequest
	GetPhysiqueResponse
*/
package dongfeng_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
