// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

/*
Package dongfeng_protobuf is a generated protocol buffer package.

It is generated from these files:
	github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

It has these top-level messages:
	DashboardRequest
	DashboardResponse
	LoginRequest
	LoginResponse
	UploadAvatarResponse
	User
	Setting
	Notification
	UpdateUserRequest
	UpdateUserResponse
	GetNamelistRequest
	GetNamelistResponse
	NamelistItem
	UpdateAttendanceRequest
	ClassAttendance
	UpdateAttendanceResponse
	GetAttendanceRequest
	GetAttendanceResponse
	Attendance
	UpdatePhysiqueRequest
	Physique
	PhysiqueItem
	UpdatePhysiqueResponse
	GetPhysiqueRequest
	GetPhysiqueResponse
	UpdateRecipeRequest
	UpdateRecipeResponse
*/
package dongfeng_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
