// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

package dongfeng_protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ******************************************************* message definition *******************************************************
///////////////////////////////////////////////////
type DashboardRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashboardRequest) Reset()         { *m = DashboardRequest{} }
func (m *DashboardRequest) String() string { return proto.CompactTextString(m) }
func (*DashboardRequest) ProtoMessage()    {}
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{0}
}

func (m *DashboardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardRequest.Unmarshal(m, b)
}
func (m *DashboardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardRequest.Marshal(b, m, deterministic)
}
func (m *DashboardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardRequest.Merge(m, src)
}
func (m *DashboardRequest) XXX_Size() int {
	return xxx_messageInfo_DashboardRequest.Size(m)
}
func (m *DashboardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardRequest proto.InternalMessageInfo

func (m *DashboardRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type DashboardResponse struct {
	UserId               string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Notifications        []*Notification `protobuf:"bytes,2,rep,name=notifications,proto3" json:"notifications"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DashboardResponse) Reset()         { *m = DashboardResponse{} }
func (m *DashboardResponse) String() string { return proto.CompactTextString(m) }
func (*DashboardResponse) ProtoMessage()    {}
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{1}
}

func (m *DashboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardResponse.Unmarshal(m, b)
}
func (m *DashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardResponse.Marshal(b, m, deterministic)
}
func (m *DashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardResponse.Merge(m, src)
}
func (m *DashboardResponse) XXX_Size() int {
	return xxx_messageInfo_DashboardResponse.Size(m)
}
func (m *DashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardResponse proto.InternalMessageInfo

func (m *DashboardResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DashboardResponse) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

///////////////////////////////////////////////////
type LoginRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

///////////////////////////////////////////////////
type UploadAvatarResponse struct {
	Uri                  string   `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadAvatarResponse) Reset()         { *m = UploadAvatarResponse{} }
func (m *UploadAvatarResponse) String() string { return proto.CompactTextString(m) }
func (*UploadAvatarResponse) ProtoMessage()    {}
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{4}
}

func (m *UploadAvatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadAvatarResponse.Unmarshal(m, b)
}
func (m *UploadAvatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadAvatarResponse.Marshal(b, m, deterministic)
}
func (m *UploadAvatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadAvatarResponse.Merge(m, src)
}
func (m *UploadAvatarResponse) XXX_Size() int {
	return xxx_messageInfo_UploadAvatarResponse.Size(m)
}
func (m *UploadAvatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadAvatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadAvatarResponse proto.InternalMessageInfo

func (m *UploadAvatarResponse) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

///////////////////////////////////////////////////
type User struct {
	Newuser              bool       `protobuf:"varint,1,opt,name=newuser,proto3" json:"newuser"`
	Role                 string     `protobuf:"bytes,2,opt,name=role,proto3" json:"role"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id"`
	Email                string     `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Name                 string     `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Avatar               string     `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar"`
	Settings             []*Setting `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{5}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNewuser() bool {
	if m != nil {
		return m.Newuser
	}
	return false
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

///////////////////////////////////////////////////
type Setting struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{6}
}

func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (m *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(m, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Setting) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

///////////////////////////////////////////////////
type Notification struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	CustomCode           string   `protobuf:"bytes,3,opt,name=custom_code,json=customCode,proto3" json:"custom_code"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category"`
	Details              string   `protobuf:"bytes,5,opt,name=details,proto3" json:"details"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link"`
	Time                 string   `protobuf:"bytes,7,opt,name=time,proto3" json:"time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{7}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Notification) GetCustomCode() string {
	if m != nil {
		return m.CustomCode
	}
	return ""
}

func (m *Notification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notification) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Notification) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Notification) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

///////////////////////////////////////////////////
type UpdateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{8}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{9}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

///////////////////////////////////////////////////
type AttendanceRequest struct {
	Token                string             `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	Attendances          []*ClassAttendance `protobuf:"bytes,2,rep,name=attendances,proto3" json:"attendances"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AttendanceRequest) Reset()         { *m = AttendanceRequest{} }
func (m *AttendanceRequest) String() string { return proto.CompactTextString(m) }
func (*AttendanceRequest) ProtoMessage()    {}
func (*AttendanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{10}
}

func (m *AttendanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendanceRequest.Unmarshal(m, b)
}
func (m *AttendanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendanceRequest.Marshal(b, m, deterministic)
}
func (m *AttendanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendanceRequest.Merge(m, src)
}
func (m *AttendanceRequest) XXX_Size() int {
	return xxx_messageInfo_AttendanceRequest.Size(m)
}
func (m *AttendanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttendanceRequest proto.InternalMessageInfo

func (m *AttendanceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AttendanceRequest) GetAttendances() []*ClassAttendance {
	if m != nil {
		return m.Attendances
	}
	return nil
}

type ClassAttendance struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day"`
	Class                string   `protobuf:"bytes,4,opt,name=class,proto3" json:"class"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Attendances          []int32  `protobuf:"varint,6,rep,packed,name=attendances,proto3" json:"attendances"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassAttendance) Reset()         { *m = ClassAttendance{} }
func (m *ClassAttendance) String() string { return proto.CompactTextString(m) }
func (*ClassAttendance) ProtoMessage()    {}
func (*ClassAttendance) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{11}
}

func (m *ClassAttendance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassAttendance.Unmarshal(m, b)
}
func (m *ClassAttendance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassAttendance.Marshal(b, m, deterministic)
}
func (m *ClassAttendance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassAttendance.Merge(m, src)
}
func (m *ClassAttendance) XXX_Size() int {
	return xxx_messageInfo_ClassAttendance.Size(m)
}
func (m *ClassAttendance) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassAttendance.DiscardUnknown(m)
}

var xxx_messageInfo_ClassAttendance proto.InternalMessageInfo

func (m *ClassAttendance) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ClassAttendance) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *ClassAttendance) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *ClassAttendance) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *ClassAttendance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClassAttendance) GetAttendances() []int32 {
	if m != nil {
		return m.Attendances
	}
	return nil
}

type AttendanceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttendanceResponse) Reset()         { *m = AttendanceResponse{} }
func (m *AttendanceResponse) String() string { return proto.CompactTextString(m) }
func (*AttendanceResponse) ProtoMessage()    {}
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d37d3dc0bc109b, []int{12}
}

func (m *AttendanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttendanceResponse.Unmarshal(m, b)
}
func (m *AttendanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttendanceResponse.Marshal(b, m, deterministic)
}
func (m *AttendanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttendanceResponse.Merge(m, src)
}
func (m *AttendanceResponse) XXX_Size() int {
	return xxx_messageInfo_AttendanceResponse.Size(m)
}
func (m *AttendanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttendanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttendanceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DashboardRequest)(nil), "dongfeng.protobuf.DashboardRequest")
	proto.RegisterType((*DashboardResponse)(nil), "dongfeng.protobuf.DashboardResponse")
	proto.RegisterType((*LoginRequest)(nil), "dongfeng.protobuf.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "dongfeng.protobuf.LoginResponse")
	proto.RegisterType((*UploadAvatarResponse)(nil), "dongfeng.protobuf.UploadAvatarResponse")
	proto.RegisterType((*User)(nil), "dongfeng.protobuf.User")
	proto.RegisterType((*Setting)(nil), "dongfeng.protobuf.Setting")
	proto.RegisterType((*Notification)(nil), "dongfeng.protobuf.Notification")
	proto.RegisterType((*UpdateUserRequest)(nil), "dongfeng.protobuf.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "dongfeng.protobuf.UpdateUserResponse")
	proto.RegisterType((*AttendanceRequest)(nil), "dongfeng.protobuf.AttendanceRequest")
	proto.RegisterType((*ClassAttendance)(nil), "dongfeng.protobuf.ClassAttendance")
	proto.RegisterType((*AttendanceResponse)(nil), "dongfeng.protobuf.AttendanceResponse")
}

func init() {
	proto.RegisterFile("github.com/ilovelili/dongfeng-protobuf/dongfeng.proto", fileDescriptor_25d37d3dc0bc109b)
}

var fileDescriptor_25d37d3dc0bc109b = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x41, 0x6b, 0xdb, 0x4c,
	0x10, 0xc5, 0xb2, 0x65, 0xf9, 0x1b, 0x27, 0x5f, 0xe3, 0xc5, 0x34, 0x22, 0x97, 0x98, 0xa5, 0x07,
	0x43, 0xa9, 0x03, 0x29, 0xed, 0xa9, 0x97, 0x90, 0x94, 0x52, 0x28, 0x3d, 0xa8, 0xf8, 0x1c, 0x56,
	0xda, 0xb1, 0xb2, 0x44, 0xda, 0x75, 0xb5, 0xab, 0x14, 0xff, 0x94, 0xfe, 0x91, 0x1e, 0xfb, 0xdb,
	0xca, 0xee, 0x4a, 0xaa, 0xdc, 0x18, 0xdf, 0xe6, 0x0d, 0x6f, 0x76, 0xde, 0xbc, 0x99, 0x85, 0x77,
	0xb9, 0x30, 0x0f, 0x75, 0xba, 0xca, 0x54, 0x79, 0x25, 0x0a, 0xf5, 0x84, 0x85, 0x28, 0xc4, 0x15,
	0x57, 0x32, 0xdf, 0xa0, 0xcc, 0xdf, 0x6c, 0x2b, 0x65, 0x54, 0x5a, 0x6f, 0xba, 0xcc, 0xca, 0x65,
	0xc8, 0x6c, 0x1f, 0xa7, 0xf5, 0x86, 0x2e, 0xe1, 0xec, 0x8e, 0xe9, 0x87, 0x54, 0xb1, 0x8a, 0x27,
	0xf8, 0xbd, 0x46, 0x6d, 0xc8, 0x1c, 0x42, 0xa3, 0x1e, 0x51, 0xc6, 0x83, 0xc5, 0x60, 0xf9, 0x5f,
	0xe2, 0x01, 0xd5, 0x30, 0xeb, 0x31, 0xf5, 0x56, 0x49, 0x8d, 0xe4, 0x1c, 0xa2, 0x5a, 0x63, 0x75,
	0x2f, 0x78, 0x43, 0x1e, 0x5b, 0xf8, 0x99, 0x93, 0x8f, 0x70, 0x2a, 0x95, 0x11, 0x1b, 0x91, 0x31,
	0x23, 0x94, 0xd4, 0x71, 0xb0, 0x18, 0x2e, 0xa7, 0xd7, 0x97, 0xab, 0x67, 0x12, 0x56, 0x5f, 0x7b,
	0xbc, 0x64, 0xbf, 0x8a, 0xbe, 0x82, 0x93, 0x2f, 0x2a, 0x17, 0xf2, 0xb8, 0xb4, 0x0f, 0x70, 0xda,
	0xb0, 0x1a, 0x59, 0xaf, 0x61, 0x64, 0x75, 0x38, 0xd6, 0xf4, 0xfa, 0xfc, 0x40, 0xd3, 0xb5, 0xc6,
	0x2a, 0x71, 0x24, 0xba, 0x84, 0xf9, 0x7a, 0x5b, 0x28, 0xc6, 0x6f, 0x9e, 0x98, 0x61, 0x55, 0xf7,
	0xc8, 0x19, 0x0c, 0xeb, 0x4a, 0x34, 0x9d, 0x6c, 0x48, 0x7f, 0x0f, 0x60, 0x64, 0x0b, 0x49, 0x0c,
	0x91, 0xc4, 0x1f, 0x5d, 0x8b, 0x49, 0xd2, 0x42, 0x42, 0x60, 0x54, 0xa9, 0x02, 0xe3, 0xc0, 0x55,
	0xb9, 0x98, 0xfc, 0x0f, 0x81, 0xe0, 0xf1, 0xd0, 0x65, 0x02, 0xc1, 0xed, 0x10, 0x58, 0x32, 0x51,
	0xc4, 0x23, 0x3f, 0x84, 0x03, 0xb6, 0x52, 0xb2, 0x12, 0xe3, 0xd0, 0x57, 0xda, 0x98, 0xbc, 0x84,
	0x31, 0x73, 0xa2, 0xe2, 0xb1, 0x77, 0xd7, 0x23, 0xf2, 0x1e, 0x26, 0x1a, 0x8d, 0x11, 0x32, 0xd7,
	0x71, 0xe4, 0x8c, 0xbd, 0x38, 0x30, 0xe3, 0x37, 0x4f, 0x49, 0x3a, 0x2e, 0xfd, 0x04, 0x51, 0x93,
	0x6c, 0x44, 0x59, 0xf5, 0xa1, 0x13, 0xd5, 0xb6, 0x0f, 0x7a, 0xed, 0x63, 0x88, 0x50, 0xb2, 0xb4,
	0x40, 0xaf, 0x7e, 0x92, 0xb4, 0x90, 0xfe, 0x1a, 0xc0, 0x49, 0x7f, 0x6f, 0xcf, 0x9e, 0xeb, 0x1d,
	0x46, 0xb0, 0x77, 0x18, 0x97, 0x30, 0xcd, 0x6a, 0x6d, 0x54, 0x79, 0x9f, 0x29, 0x8e, 0x8d, 0x2b,
	0xe0, 0x53, 0xb7, 0x8a, 0x23, 0xb9, 0x80, 0x49, 0xc6, 0x0c, 0xe6, 0xaa, 0xda, 0x35, 0x06, 0x75,
	0xd8, 0x0a, 0xe2, 0x68, 0x98, 0x28, 0x74, 0x63, 0x53, 0x0b, 0xad, 0xfc, 0x42, 0xc8, 0xc7, 0xc6,
	0x27, 0x17, 0xdb, 0x9c, 0x11, 0x25, 0xc6, 0x91, 0xcf, 0xd9, 0x98, 0xae, 0x61, 0xb6, 0xde, 0x72,
	0x66, 0xd0, 0x1d, 0xc0, 0xb1, 0xab, 0x3a, 0xe8, 0xc8, 0xdf, 0x85, 0x0c, 0xfb, 0x0b, 0xa1, 0x73,
	0x20, 0xfd, 0x67, 0xfd, 0x05, 0x51, 0x05, 0xb3, 0x1b, 0x63, 0x50, 0x72, 0x26, 0x33, 0x3c, 0xde,
	0xec, 0x0e, 0xa6, 0xac, 0xa3, 0xb6, 0xbf, 0x85, 0x1e, 0x58, 0xea, 0x6d, 0xc1, 0xb4, 0xee, 0xbd,
	0xda, 0x2f, 0xa3, 0x3f, 0x07, 0xf0, 0xe2, 0x1f, 0x82, 0x1d, 0x63, 0x87, 0xac, 0x6a, 0x76, 0xe3,
	0x62, 0xab, 0xa1, 0x54, 0xd2, 0x3c, 0xb8, 0xd9, 0xc2, 0xc4, 0x03, 0x7b, 0xf0, 0x9c, 0xed, 0xdc,
	0x64, 0x61, 0x62, 0x43, 0xcb, 0xcb, 0xec, 0x73, 0xed, 0xa5, 0x3a, 0x70, 0xf0, 0x52, 0x17, 0xfb,
	0xfa, 0xc7, 0x8b, 0xe1, 0x32, 0xdc, 0xd7, 0x36, 0x07, 0xd2, 0x37, 0xc3, 0x5b, 0x94, 0x8e, 0xdd,
	0x60, 0x6f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xee, 0xab, 0xd0, 0xfc, 0xd2, 0x04, 0x00, 0x00,
}
