// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

package dongfeng_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ******************************************************* message definition *******************************************************
type LoginRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dongfeng_761aff23458a3694, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (dst *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(dst, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginResponse struct {
	Version              string          `protobuf:"bytes,1,opt,name=version,proto3" json:"version"`
	User                 *User           `protobuf:"bytes,2,opt,name=user,proto3" json:"user"`
	Notifications        []*Notification `protobuf:"bytes,3,rep,name=notifications,proto3" json:"notifications"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dongfeng_761aff23458a3694, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type User struct {
	Newuser              bool       `protobuf:"varint,1,opt,name=newuser,proto3" json:"newuser"`
	Role                 string     `protobuf:"bytes,2,opt,name=role,proto3" json:"role"`
	Id                   string     `protobuf:"bytes,3,opt,name=id,proto3" json:"id"`
	Email                string     `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Name                 string     `protobuf:"bytes,5,opt,name=name,proto3" json:"name"`
	Avatar               string     `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar"`
	Settings             []*Setting `protobuf:"bytes,7,rep,name=settings,proto3" json:"settings"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_dongfeng_761aff23458a3694, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetNewuser() bool {
	if m != nil {
		return m.Newuser
	}
	return false
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Setting struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_dongfeng_761aff23458a3694, []int{3}
}
func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (dst *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(dst, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Setting) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Setting) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type Notification struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	CustomCode           string   `protobuf:"bytes,3,opt,name=custom_code,json=customCode,proto3" json:"custom_code"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category"`
	Details              string   `protobuf:"bytes,5,opt,name=details,proto3" json:"details"`
	Link                 string   `protobuf:"bytes,6,opt,name=link,proto3" json:"link"`
	Time                 string   `protobuf:"bytes,7,opt,name=time,proto3" json:"time"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_dongfeng_761aff23458a3694, []int{4}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Notification) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Notification) GetCustomCode() string {
	if m != nil {
		return m.CustomCode
	}
	return ""
}

func (m *Notification) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Notification) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func (m *Notification) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Notification) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "dongfeng.protobuf.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "dongfeng.protobuf.LoginResponse")
	proto.RegisterType((*User)(nil), "dongfeng.protobuf.User")
	proto.RegisterType((*Setting)(nil), "dongfeng.protobuf.Setting")
	proto.RegisterType((*Notification)(nil), "dongfeng.protobuf.Notification")
}

func init() {
	proto.RegisterFile("github.com/ilovelili/dongfeng-protobuf/dongfeng.proto", fileDescriptor_dongfeng_761aff23458a3694)
}

var fileDescriptor_dongfeng_761aff23458a3694 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x6a, 0x14, 0x41,
	0x10, 0xc6, 0x99, 0xfd, 0x37, 0x9b, 0xda, 0x44, 0xb0, 0x11, 0xd3, 0xe4, 0x92, 0x65, 0xf0, 0xb0,
	0x20, 0x6e, 0x20, 0xa2, 0x2f, 0x20, 0x22, 0x82, 0x78, 0x18, 0xf1, 0x1c, 0x7a, 0xa6, 0x6b, 0xc7,
	0x22, 0x3d, 0x5d, 0x71, 0xba, 0x67, 0xc5, 0x87, 0xf1, 0x35, 0x3c, 0xfa, 0x6c, 0xd2, 0x3d, 0x3d,
	0xcb, 0x86, 0xec, 0xad, 0x7e, 0x1f, 0xf5, 0xe7, 0xab, 0x0f, 0xde, 0x35, 0xe4, 0x7f, 0xf4, 0xd5,
	0xb6, 0xe6, 0xf6, 0x86, 0x0c, 0xef, 0xd1, 0x90, 0xa1, 0x1b, 0xcd, 0xb6, 0xd9, 0xa1, 0x6d, 0xde,
	0x3c, 0x74, 0xec, 0xb9, 0xea, 0x77, 0x07, 0x65, 0x1b, 0x15, 0xf1, 0xfc, 0x31, 0x57, 0xfd, 0xae,
	0x78, 0x05, 0xe7, 0x5f, 0xb8, 0x21, 0x5b, 0xe2, 0xcf, 0x1e, 0x9d, 0x17, 0x2f, 0x60, 0xee, 0xf9,
	0x1e, 0xad, 0xcc, 0xd6, 0xd9, 0xe6, 0xac, 0x1c, 0xa0, 0xf8, 0x93, 0xc1, 0x45, 0x6a, 0x73, 0x0f,
	0x6c, 0x1d, 0x0a, 0x09, 0xf9, 0x1e, 0x3b, 0x47, 0x3c, 0x76, 0x8e, 0x28, 0x5e, 0xc3, 0xac, 0x77,
	0xd8, 0xc9, 0xc9, 0x3a, 0xdb, 0xac, 0x6e, 0x2f, 0xb7, 0x4f, 0x6e, 0x6e, 0xbf, 0x3b, 0xec, 0xca,
	0xd8, 0x24, 0x3e, 0xc2, 0x85, 0x65, 0x4f, 0x3b, 0xaa, 0x95, 0x27, 0xb6, 0x4e, 0x4e, 0xd7, 0xd3,
	0xcd, 0xea, 0xf6, 0xfa, 0xc4, 0xd4, 0xd7, 0xa3, 0xbe, 0xf2, 0xf1, 0x54, 0xf1, 0x2f, 0x83, 0x59,
	0xd8, 0x1a, 0x6c, 0x59, 0xfc, 0x15, 0xef, 0x07, 0x5b, 0xcb, 0x72, 0x44, 0x21, 0x60, 0xd6, 0xb1,
	0xc1, 0x68, 0xeb, 0xac, 0x8c, 0xb5, 0x78, 0x06, 0x13, 0xd2, 0x72, 0x1a, 0x95, 0x09, 0xe9, 0xf0,
	0x3c, 0xb6, 0x8a, 0x8c, 0x9c, 0x0d, 0xcf, 0x47, 0x08, 0x93, 0x56, 0xb5, 0x28, 0xe7, 0xc3, 0x64,
	0xa8, 0xc5, 0x4b, 0x58, 0xa8, 0xbd, 0xf2, 0xaa, 0x93, 0x8b, 0xa8, 0x26, 0x12, 0xef, 0x61, 0xe9,
	0xd0, 0x7b, 0xb2, 0x8d, 0x93, 0x79, 0x7c, 0xe5, 0xea, 0xc4, 0x2b, 0xdf, 0x86, 0x96, 0xf2, 0xd0,
	0x5b, 0x7c, 0x82, 0x3c, 0x89, 0xc9, 0x54, 0x70, 0x3f, 0x8f, 0xa6, 0xc6, 0xf3, 0x93, 0xa3, 0xf3,
	0x12, 0x72, 0xb4, 0xaa, 0x32, 0x38, 0xb8, 0x5f, 0x96, 0x23, 0x16, 0x7f, 0x33, 0x38, 0x3f, 0x4e,
	0xea, 0xc9, 0xba, 0x4b, 0xc8, 0x43, 0x1e, 0x77, 0xa4, 0xd3, 0xc6, 0x45, 0xc0, 0xcf, 0x5a, 0x5c,
	0xc3, 0xaa, 0xee, 0x9d, 0xe7, 0xf6, 0xae, 0x66, 0x8d, 0x29, 0x15, 0x18, 0xa4, 0x0f, 0xac, 0x51,
	0x5c, 0xc1, 0xb2, 0x56, 0x1e, 0x1b, 0xee, 0x7e, 0xa7, 0x80, 0x0e, 0x1c, 0x0c, 0x69, 0xf4, 0x8a,
	0x8c, 0x4b, 0x31, 0x8d, 0x18, 0xec, 0x1b, 0xb2, 0xf7, 0x29, 0xa7, 0x58, 0x07, 0xcd, 0x53, 0x8b,
	0x32, 0x1f, 0xb4, 0x50, 0x57, 0x8b, 0x98, 0xce, 0xdb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d,
	0x5b, 0x82, 0x37, 0xdb, 0x02, 0x00, 0x00,
}
