// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

/*
Package dongfeng_protobuf is a generated protocol buffer package.

It is generated from these files:
	github.com/ilovelili/dongfeng-protobuf/dongfeng.proto

It has these top-level messages:
	DashboardRequest
	DashboardResponse
	LoginRequest
	LoginResponse
	User
	UploadAvatarResponse
	Setting
	UpdateNotificationsRequest
	UpdateNotificationsResponse
	UpdateNotificationRequest
	UpdateNotificationResponse
	Notification
	UpdateUserRequest
	UpdateUserResponse
	GetClassRequest
	GetClassResponse
	UpdateClassRequest
	UpdateClassResponse
	Class
	GetPupilRequest
	GetPupilResponse
	UpdatePupilRequest
	UpdatePupilResponse
	Pupil
	GetTeacherRequest
	GetTeacherResponse
	UpdateTeacherRequest
	UpdateTeacherResponse
	Teacher
	GetAttendanceRequest
	GetAttendanceResponse
	UpdateAttendanceRequest
	UpdateAttendanceResponse
	Attendance
	Holiday
	CountAttendanceRequest
	CountAttendanceResponse
	AttendanceCount
	UpdatePhysiqueRequest
	UpdatePhysiqueResponse
	Physique
	GetPhysiqueRequest
	GetPhysiqueResponse
	GetAgeHeightWeightPMasterRequest
	GetAgeHeightWeightPMasterResponse
	AgeHeightWeightPMaster
	GetAgeHeightWeightSDMasterRequest
	GetAgeHeightWeightSDMasterResponse
	AgeHeightWeightSDMaster
	GetBMIMasterRequest
	GetBMIMasterResponse
	BMIMaster
	GetHeightToWeightPMasterRequest
	GetHeightToWeightPMasterResponse
	HeightToWeightPMaster
	GetHeightToWeightSDMasterRequest
	GetHeightToWeightSDMasterResponse
	HeightToWeightSDMaster
	GetMenuRequest
	GetMenuResponse
	UpdateMenuRequest
	UpdateMenuResponse
	Menu
	GetRecipeRequest
	GetRecipeResponse
	UpdateRecipeRequest
	UpdateRecipeResponse
	Recipe
	GetIngredientRequest
	GetIngredientResponse
	GetIngredientNameRequest
	GetIngredientNameResponse
	UpdateIngredientRequest
	UpdateIngredientResponse
	Ingredient
	GetProcurementRequest
	GetProcurementResponse
	Procurement
	IngredientAmount
	GetProfileRequest
	GetProfileResponse
	GetPrevOrNextProfileRequest
	GetPrevOrNextProfileResponse
	UpdateProfileRequest
	UpdateProfileResponse
	GetProfilesRequest
	GetProfilesResponse
	Profile
*/
package dongfeng_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
